### ISSUE TITLE
Slider Enhancement

### ISSUE THREAD

**Issue by smaca69** [artisan-roaster-scope/artisan#1156]
Would it be possible to have sliders with labels that would allow you to move it directly to a setting without trying to move the slider to the exact value.  Please refer to the image below.
For example, as per the attached image, if I wanted to move the gas setting to 40%, i would just click on the 40% label next to the slider.  This would save me needing to create lots of buttons which could do the same thing but would clutter my button section of the screen.

![IMG-0174](https://user-images.githubusercontent.com/20550292/235418150-2957997c-8615-44de-8793-293011ce810a.jpg)

**Comment by MAKOMO** [comment]
Yes, totally possible, but not a target within the available resource of the core Artisan team. 

However, as Artisan is open-source you are welcome to implement this one. If you'd like to have this integrated into the Artisan trunk please open a PR with the changes and make sure they run on all supported platforms and with all supported hardware. Otherwise you might want to check out Cropster which already implements this.
