### ISSUE TITLE
Humidity ambient phidget temperature reports incorrectly as pressure

### ISSUE THREAD

**Issue by wab0111** [artisan-roaster-scope/artisan#1189]
I am using a Hottop 2k+ with the ambient phidget devices for humidity, temperature, and pressure. The devices read correctly on their corresponding LCD's and roast properties dialog box. When I save a pdf report, the ambient temperature is presenting the ambient pressure reading where the temperature should be. 

I am using Artisan 2.8.2 on Linux (Lubuntu 23.04).
Connected devices:
- Hottop 2k+
- Phidget: HUB0001, HUM1000, PRE1000

[Screenshot](https://imgur.com/a/6d1HyoN)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]:
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]:
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]:
 - Connected devices or roasting machine [e.g. Probatone 5]:

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
I am not able to reproduce this. To investigate further will require having your current settings file and the profile used to create this report. 

Do not email the attachments, you need to come here to GitHub, then drag them into a reply. 


Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

Note that you need either add a .txt extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading.

**Comment by wab0111** [comment]
Here is the profile file. I renamed the extension from alog to zip.
[Roast Report C10 23-06-01.zip](https://github.com/artisan-roaster-scope/artisan/files/11627826/Roast.Report.C10.23-06-01.zip)

**Comment by roasterdave** [comment]
There is a problem with your setup.  The HUM100x and PRE1000 Phidgets are not available as Extra Devices and cannot be read from the Phidget HUB IO ports.   The ambient values are read only at the beginning of the roast from the devices defined on the Config>> Device>> Ambient tab.  Once read their values can be seen on the Roast>> Roast Properties> Roast tab.  They are also available for use in symbolic formulas as aPRE, aHUM and aTMP.  As a result of trying to read the HUB IO ports and then overwriting with the symbolic data, the ambient temperature value got altered somewhere during the roast.  We will look into why that happened.  Nevertheless, the configuration still will not give you dynamic values during the roast.

The settings you have on the Config>> Device>> Ambient tab are correct.  If you want these ambient values displayed in the LCDs you should change those device types to be Virtual (instead of Phidget HUB IO) as shown below.  Leave the Labels, y1(x) and y2(x) as they are.  If you don't care about showing these static values in LCDs simply delete these two Extra Devices.

![image](https://github.com/artisan-roaster-scope/artisan/assets/30009312/f7821276-5c12-496d-97d0-678c6cacd4e6)

**Comment by MAKOMO** [comment]
Hi Dave,Thanks for your wishes. I hope not to block the others too much today. Thanks for answering my Hose two issues. There is a new pymodbus and PyQt out now.MSent from my iPhoneOn 2. Jun 2023, at 23:13, Dave Baxter ***@***.***> wrote:﻿
There is a problem with your setup.  The HUM100x and PRE1000 Phidgets are not available as Extra Devices and cannot be read from the Phidget HUB IO ports.   The ambient values are read only at the beginning of the roast from the devices defined on the Config>> Device>> Ambient tab.  Once read their values can be seen on the Roast>> Roast Properties> Roast tab.  They are also available for use in symbolic formulas as aPRE, aHUM and aTMP.  As a result of trying to read the HUB IO ports and then overwriting with the symbolic data, the ambient temperature value got altered somewhere during the roast.  We will look into why that happened.  Nevertheless, the configuration still will not give you dynamic values during the roast.
The settings you have on the Config>> Device>> Ambient tab are correct.  If you want these ambient values displayed in the LCDs you should change those device types to be Virtual (instead of Phidget HUB IO) as shown below.  Leave the Labels, y1(x) and y2(x) as they are.  If you don't care about showing these static values in LCDs simply delete these two Extra Devices.
