### ISSUE TITLE
Can't initialize Phidget servo with On Event

### ISSUE THREAD

**Issue by srosemer** [artisan-roaster-scope/artisan#1211]
**Describe the bug**
When attempting to initialize a Phidget controlled servo motor using the wireless hub and 16-port servo controller, Artisan is unable to reliably initialize and set the position of a servo using the "On" event button.  

**To Reproduce**
1. Go to 'Config Events'
2. Click on 'Config Tab'
3. Select RC Command drop-down in "On" Event Button
4. Enter command:  set(0,150, 727171:0);engaged(0,1, 727171:0);pulse(0,500,2500, 727171:0)

where, 0 is the servo port, 727171:0 is the hub serial and port, 150 is the servo position, and 500/2500 is the pulse-width of the servo of interest.

**Expected behavior**
Set the servo position to ~150, and configure the pulse width ranges (tested using the Phidget control panel, setting the pulse width prior to setting position and engagement throws an error).

I am able to get the servo to successfully initialize if I use a custom event button; however, I must send the "set(0,150, 727171:0)" command twice, the set engaged, followed by the pulse-width.

**Screenshots**
N/A -

**Setup (please complete the following information):**
 - Artisan Version: v2.80
 - Artisan Build (number in brackets shown in the about box): 49b6c9c
 - Platform (Mac/Windows/Linux + OS version)]: Mac OS 12.6.3
 - Connected devices or roasting machine:  BC 3.5 

**Additional context**
Other Phidget devices I have connected (all sensors) successfully connect and start logging data coincident with selecting the "On" event.  The servo connected to the servo controller is a Bilda 2000 series 5-turn servo. 

Servo may also lose connection and require re-initialization when resetting scope and selecting a different background curve.

**Comment by MAKOMO** [comment]
Why are you using an outdated Artisan version? Current version is v2.8.4. 

Commands are processed in order. Thus you need first to set the pulse-width before setting a position. Otherwise, the device will use its default pulse-width to interpret the position you set.

> setting the pulse width prior to setting position and engagement throws an error
I can not duplicate this. Maybe an error in the Phidget Control Panel?

Are you using the latest Phidget driver (v1.15.20230616), and the latest firmware versions for your Phidget hub and the RC module?

`Servo may also lose connection and require re-initialization when resetting scope and selecting a different background curve.`
Selecting a different background curve has no influence on any Phidget communication. Thus loading an Artisan settings will reset any communication.
