### ISSUE TITLE
The error found when setting Filters.

### ISSUE THREAD

**Issue by fwrowe** [artisan-roaster-scope/artisan#1406]
I noticed that when setting the Filters, the numerical values for Celsius and Fahrenheit are identical, with only the units changing. This default setting is not user-friendly and has caused me confusion.I am not sure about the meaning of these default values, whether they are in Fahrenheit or Celsius, or what values would be better to change them to.

I look forward to your prompt attention to this matter.
![The error found when setting Filters](https://github.com/artisan-roaster-scope/artisan/assets/156916700/9d7aa105-4ab6-4c51-baed-1bbc4fa63295)

**Comment by MAKOMO** [comment]
The input filter min/max limits don't carry a unit as they are applied directly to the readings received independent if those are in C, F, Volt, Amper,... Therefore those limits are not adjusted based on the temperature unit selected and the filter is deactivated by default (not ticked as in your screenshots) as this filter should only be applied if absolutely needed and can lead to confusing situations otherwise.

The values of the "Interpolate Duplicates" input filter as well as the RoR min/max limits should be adjusted on changing the temperature unit. This will be added to the next Artisan version. Thanks for your report!

Fixed in commit 8807ac10984f2c603fd8cf328b363d70356e2c26.
