### ISSUE TITLE
Buhler Roastmaster S7 communication error

### ISSUE THREAD

**Issue by jaejun78** [artisan-roaster-scope/artisan#1529]
### Problem Description

While roast progress, it shows error messages below,
======================================================
readActiveRegisters() S7 Communication Error: read_area(5,1061,16,2)@line 341
======================================================

Any other numbers shows well without errors, just error messages shows continuously 
I found this error after 2.10 version. 2.10.4 version still has same problem.

![image](https://github.com/artisan-roaster-scope/artisan/assets/61921943/ff3817c0-000d-46f3-b211-c7c00279cc66)

### Steps To Reproduce

1. Setup machine buhler roastmaster20 simatic.
2. enter IP address.
3. start.

### Artisan Version

2.10.0

### Computer OS and Version

Windows 11, Windows 10, any other linux machines

### Connected devices or roasting machine

Buhler roastmaster20

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
This is a configuration issue. While we implemented the connection to Bühler machines according to the companies specification, it seems that there are some machines (maybe running older firmware versions!?) that do not support the retrieval of the machines state as documented.

The fix is easy. Just deactivate that S7 channel by setting the `Area` of input 6 to the empty entry such that this data is no longer requested from the machine.

<img width="1072" alt="Screenshot 2024-04-02 at 09 49 46" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/0e0f07de-0298-4fe6-ae46-97c6b6d91128">


You should also remove those two alarm rules are that refer to this machine state

<img width="1028" alt="Screenshot 2024-04-02 at 09 50 13" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/b457e721-2e4d-40cc-b8ef-0ea8691fab14">

We will add a machine setup `RM 20 Simatic Legacy` which will provide those changes with the next Artisan version.

**Comment by jaejun78** [comment]
While I asked a dumb question, but great answer!!Thank you so much!!
