### ISSUE TITLE
RoR curve incorrect during roast

### ISSUE THREAD

**Issue by Karbug** [artisan-roaster-scope/artisan#153]
Since upgrade from Artisan1.1 to Artisan1.2 on HP pc Win8.1, RoR curve begins plotting at roughly the 2:20 mark and seems to proceed normally during the roast. However, once the roast concludes and "End" button is pressed, the RoR curve jumps to the left by about one minute on the y axis so that the curve starts at 1:20. Attached are two captures of the same roast, one taken during the roast showing RoR curve starting at 2:20, the other taken post roast showing curve starting at 1:20. I believe the post roast curve shows actual correct readings but readings during the roast are incorrect. This never occurred with 1.1.
![screen shot 01-10-18 at 03 15 pm](https://user-images.githubusercontent.com/36096035/35763575-e3ceadca-0874-11e8-875d-35e95a2497b6.JPG)

![screen shot 01-10-18 at 03 25 pm](https://user-images.githubusercontent.com/36096035/35763586-1a374098-0875-11e8-9628-9c13f3c6d2d2.JPG)

**Comment by MAKOMO** [comment]
Dear Karburg,

> On 3. Feb 2018, at 07:01, Karbug <notifications@github.com> wrote:
> 
> Since upgrade from Artisan1.1 to Artisan1.2 on HP pc Win8.1, RoR curve begins plotting at roughly the 2:20 mark and seems to proceed normally during the roast. However, once the roast concludes and "End" button is pressed, the RoR curve jumps to the left by about one minute on the y axis so that the curve starts at 1:20. Attached are two captures of the same roast, one taken during the roast showing RoR curve starting at 2:20, the other taken post roast showing curve starting at 1:20. I believe the post roast curve shows actual correct readings but readings during the roast are incorrect. This never occurred with 1.1.

What you describe is the expected behaviour and the time-shift is caused by the online smoothing algorithm. Reduce your smoothing settings and the shift-error will reduce. This time-shift is not avoidable in the online-case, basically because the future is largely unknown (cf. https://artisan-roasterscope.blogspot.de/2014/01/sampling-interval-smoothing-and-rate-of.html). However, Artisan applies an optimal smoothing algorithm based on folding in the off-line case that does not produce any time-shift. The use of two different smoothing algorithms did not change between v1.1 and v1.2. What did change is that the not-optimal smoothing algorithm is now also applied to the background profile during recording to at least be able to compare the background/foreground RoR curves directly as they will be both shifted by the same amount. See Section "Rate-of-Rise alignment" of the v1.2 announcement on the Artisan blog: https://artisan-roasterscope.blogspot.de/2017/12/artisan-v12.html.

M

**Comment by Karbug** [comment]
Thank you Marko, issue is resolved.

⁣Sent from BlueMail ​
