### ISSUE TITLE
Alarms not properly moving sliders in Version 1.3.1

### ISSUE THREAD

**Issue by infinigrove** [artisan-roaster-scope/artisan#213]
## Expected Behavior

1 second after Start move Slider Timer to 4 
2 seconds after Start move Slider Fan to 2
3 seconds after Start move Slider Temp to 200

## Actual Behavior

On Start Slider Fan is moved to 2
1 second after Start Slider Temp is moved to 100 (there is no 100)
2 seconds after Start Slider Timer is moved to 4

## Steps to Reproduce the Problem

  1. Load settings and alarms, Click "ON", Click "START"
  2. See attached file for settings, alarms, alog and screenshot
  3. I'm attempting to improve https://github.com/infinigrove/SR700-Artisan-PDServer now that sliders are no longer locked into a range of 0-100.

Thank you for any help!

## Specifications

  - Artisan Version: Artisan 1.3.1 (1) 
  - Artisan Build (number in brackets shown in the about box): (1)
  - Platform (Mac/Windows/Linux + OS version): Linux
  - Connected devices or roasting machine: SR700
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[alarm-debug.zip](https://github.com/artisan-roaster-scope/artisan/files/2041027/alarm-debug.zip)

**Comment by MAKOMO** [comment]
Alarm actions triggering slider changes were still limited to the range 0-100. My commit just fixed that. The strange order of alarm processing in this case is caused by Artisan processing alarms only once per sampling interval, which seems to be 2sec here, firing only one of the "enabled" alarm in no specific order. This "lazy" behaviour might not change in the near future.
