### ISSUE TITLE
Artisan wifi issue

### ISSUE THREAD

**Issue by MarioP175** [artisan-roaster-scope/artisan#384]
## Actual Behavior
I have Giesen W15 and connect TPlink (tried different) wifi router to it.
During roasting sometimes (randomly) i have issues when air temperature replaces ror graph and ror graph starts to jump.

On wired connection there are no problems

## Specifications

  - Artisan Version: 1.6.1 or 2.0
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: Giesen W15

**Comment by MAKOMO** [comment]
Sounds like standard data communication issues you run into if you connect to a roaster via Wifi, usually caused by the motors of the machine that disturb the wireless communication. Nothing that can be done on the Artisan side. You need to fix your communication channel. It is always advisable to use wired connection to control an industrial machine like a roaster.
