### ISSUE TITLE
Ranking Report; Issues (#s 1 & 2) and Suggestion for both Ranking and Batch Reports (#3)

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#399]
## Expected Behavior
  1. Same units of weight in Load column

  2. Roast Identifiers included in the Nr column at the bottom of the report

  3. Units of measure removed from the individual rows of data and placed instead in the header row.

## Actual Behavior
1. Mixed units of weight in Load column. Roasts are labeled as GRAMS and AVG is labeled as OZ. (see mixed units.jpg)

2. Roast Identifiers missing in the Nr column at the bottom of the report. See ‘Top of Report (with Letters).jpg’ which does show Nr letters compared to ‘Bottom of Report (missing Letters).jpg’ which does not.

3. Each row of data (roast) has the units of measure (weight, temperature, percentage) as part of the data element (e.g. – 103g, 5oz, 462F, 49.5%). Use of this data would be much more flexible if the unit of measure was moved to the header row (e.g. – Load (g), Load (oz), Loss (%), FCs (F), DRY (%), etc.). Then, the data would be ‘clean’ (e.g. – 103, 5, 462, 49.5) and could then be cut and pasted (without clean-up) into another application for further analysis and manipulation. (Also, since every data item in a column has the same unit of measure it is a bit redundant to include the units with each and every entry.) 

## Steps to Reproduce the Problem

  1. Roasts were originally performed using OZ units for GREEN and ROASTED. With one of these completed roasts open in Artisan, went into Roast Properties and changed units from oz to grams. Then, go directly to generate a Ranking Report (Web...). The ‘mixed units.jpg’ is a snippet from the report. (The Batches Report does not appear to have this problem.)

  2. Same steps as #1

  3. Generate a Batch or Ranking Report

## Specifications

[Screen Captures.zip](https://github.com/artisan-roaster-scope/artisan/files/3693975/Screen.Captures.zip)
version = 2.0.0 (a0a1face)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = v3.7.3
Python Build = ('v3.7.3:ef4ec6ed12', 'Mar 25 2019 22:22:05')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = ef4ec6ed12
Python version = 3.7.3
Release = 10

  - Connected devices or roasting machine: N/A
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for this detailed report. Your point 2 was already resolved in the current trunk. Your point 1 is resolved by Commit c44cd396f2ea91388455f2d1a345a9b8558fa426 which takes your suggestion (point 3) on moving the units from the individual entries to the header column. The changes are already in the current v2.0.1 builds which you find under https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous

Note that the CSV and Excel ranking and production reports already carry the units in the table header in Artisan v2 and might be easier to work with than copy-pasted data from the generated Web pages. Sadly the Excel report is broken in the v2 builds, but is fixed in the current v2.0.1 builds.
