### ISSUE TITLE
No DeltaBT curve displayed

### ISSUE THREAD

**Issue by yokusan** [artisan-roaster-scope/artisan#531]
Error message:

"recomputedeltas() illegal values in 4-th argument of internal None@line 5793"

## Specifications

  - Artisan Version: 2.4.2 build 2
  - Artisan Build (05ca7037):
  - Platform (Mac/Windows/Linux + OS version): Windows10 Pro 64 bit
  - Connected devices or roasting machine: Bluetooth connected DIY roaster ("BilloJoe V2")

[DeltaBT Issue.zip](https://github.com/artisan-roaster-scope/artisan/files/5629122/DeltaBT.Issue.zip)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This is an issue introduced by the recent Microsoft Windows 10 Update 2004 which messes up the FPU state and thus crashes all apps that use numeric computations. This will not be fixed by Microsoft before their next update which is scheduled begin of January.

A work-around for Artisan v2.4.2 is to deactivate the Optimal Smoothing flag under menu Config >> Curve, 2nd tab. Another work-around is already implemented for the upcoming v2.4.4 of Artisan which will be released soon.
