### ISSUE TITLE
2.46 2.47  font is used for annotations within the actual profile graph display □□□   

### ISSUE THREAD

**Issue by huangdaojiri** [artisan-roaster-scope/artisan#683]
I use the win10 operating system. I set the Language as zh_CN

In artisan version 2.44 and before, the Chinese words in the circle can be displayed normally. However, in versions 2.46 and 2.47, these places display □□□

SourceHanSansCN-Regular.otf，dijkstra.ttf,Humor-Sans.ttf,WenQuanYiZenHei-01.ttf,NanumGothic,DejaVu,Sans MonoAll fonts have been installed in win10

2.47
![2.47](https://live.staticflickr.com/65535/51436751561_46e1f44ca9_k.jpg)

2.44
![2.44](https://live.staticflickr.com/65535/51436990513_858f6827dc_k.jpg)

 I will be looking forward to your reply.

**Comment by roasterdave** [comment]
Please go to Config>> Curves>> UI tab and select the font _**Source Han Sans CN**_.  Artisan has its own internal copy of these fonts so that it can run on any machine.

![Screenshot - 9_9_2021 , 1_43_46 PM](https://user-images.githubusercontent.com/30009312/132759912-249e8226-7f72-49f2-9b52-8f5ec51e49f8.png)

![Screenshot - 9_9_2021 , 1_43_59 PM](https://user-images.githubusercontent.com/30009312/132759924-44466800-afed-47be-a7dc-a5a1630e4a26.png)

![Screenshot - 9_9_2021 , 1_43_40 PM](https://user-images.githubusercontent.com/30009312/132759942-132f7360-2e9a-4018-96bb-0cef474b039a.png)

**Comment by huangdaojiri** [comment]
Thank you so much, this problem is completely resolved.

**Comment by roasterdave** [comment]
Good to hear!
