### ISSUE TITLE
BT curve and ROR lag

### ISSUE THREAD

**Issue by bolza4** [artisan-roaster-scope/artisan#907]
Hello everyone, 

I'm having a hard time tracking, at the same time, the BT curve and the ROR curve on the background. 

It seems like I can only align my current roast with the BT curve on the background OR the ROR curve, in other words I have to choose if I wanna track one curve or the other.
If I track the BT curve, I have a delay on the ROR curve, or the other way around.

How can I fix it?
thank you so much :)

![image](https://user-images.githubusercontent.com/108266430/175905084-6f3a8431-be3d-44c9-a442-89ef186f4b8f.png)

![image](https://user-images.githubusercontent.com/108266430/175905165-9ff9547d-53ef-49b7-adb9-2be98bb7f9e4.png)

matteo

**Comment by MAKOMO** [comment]
Please attach your smoothing settings here. Thanks!

**Comment by bolza4** [comment]
> 

there you go! :) thanks.

![image](https://user-images.githubusercontent.com/108266430/177040699-17275237-dbe2-4a44-bb84-8e0e40027e22.png)

**Comment by bolza4** [comment]
would you say that this smoothing settings are causing time shifts? thanks a lot :)

**Comment by bolza4** [comment]
> Please attach your smoothing settings here. Thanks!

would you say that this smoothing settings I posted above are causing time shifts? thanks a lot :)

**Comment by MAKOMO** [comment]
Yes. This is caused mostly by the strong curve smoothing here which is not applied to the foreground profile during recording. Turn that to 0 or 1 and the shift is gone. Better use directly a higher delta span for RoR smoothing.

We will limit the amount of curve smoothing in the next version and might remove it completely in a later version also due to those complications.
