### ISSUE TITLE
Artisan+ stock selection change does not carry over to roast title in Artisan Scope

### ISSUE THREAD

**Issue by HansGem** [artisan-roaster-scope/artisan#923]
**Describe the bug**
An intermittent problem has now become permanent:
IN ROAST PROPERTIES/Roast - when changing selection of coffee from Artisan+ Stock for next roast,   title no longer changes but stays with previous selection. 
On or off or reset makes no difference. To carryover I need to close Artisan and start again.
The problem was intermittent, now permamnent.
Any close much appreciated. 
Artisan is up to date  on a MacBookPro with latest Mac OS.

**Comment by MAKOMO** [comment]
The roast title changes with the selection of the beans from the artisan.plus stock only if the title field is still the unaltered default "Roaster Scope", empty, or if it corresponds to the title from the previous artisan.plus bean selection since opening the dialog. This is to prevent that a title typed in  by the user is overwritten. Note that some prefer custom roast title over the automatic generated once.

Did you modify the generated title before selecting a different bean from the artisan.plus stock?
If not, could you describe exactly the steps that lead to the behavior you describe such that we can reproduce it here and hopefully fix it.

Note: any selection of a bean from the artisan.plus stock will populate the title field with the corresponding generated title in case the title field is empty before the selection. Could this serve as a work-around?

**Comment by HansGem** [comment]
Thank you Marco - I simply ‘reset;’ and then clear and select the next coffee, and it works well for me now now. I was closing down and reopening before.

**Comment by MAKOMO** [comment]
At the bottom of the Roast Properties dialog there is a flag named "Delete Roast Properties on RESET". If this is ticked, it does exactly this. It also resets the title to its default "Roaster Scope" which in turn will be replaced by the generated title on choosing a bean from your plus repository. Of course with this ticked, all other properties in that dialog are cleared as well. Not sure this is what you want. It depends on your usage pattern.

**Comment by HansGem** [comment]
greatly appreciated! Thank you!
